/*
 * This file was generated by the Gradle "init" task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.3/userguide/java_library_plugin.html
 */
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

val onnxRuntimeVersion = "1.29.0"
val onnxRuntimeFlavor = providers.gradleProperty("onnxRuntimeFlavor").orElse("cpu")
val supportedOnnxRuntimeFlavors = setOf("cpu", "nvidia", "directml")
require(onnxRuntimeFlavor.get() in supportedOnnxRuntimeFlavors) {
	"onnxRuntimeFlavor must be one of ${supportedOnnxRuntimeFlavors.sorted()}"
}

plugins {
	kotlin("jvm")
	kotlin("plugin.serialization")
	`java-library`
}

// FIXME: Please replace these to Java 11 as that's what they actually are
kotlin {
	jvmToolchain {
		languageVersion.set(JavaLanguageVersion.of(17))
	}
}
java {
	toolchain {
		languageVersion.set(JavaLanguageVersion.of(17))
	}
}
tasks.withType<KotlinCompile> {
	compilerOptions {
		jvmTarget.set(JvmTarget.JVM_17)
		freeCompilerArgs.set(listOf("-Xvalue-classes"))
	}
}

// Set compiler to use UTF-8
tasks.withType<JavaCompile> {
	options.encoding = "UTF-8"
}
tasks.withType<Test> {
	systemProperty("file.encoding", "UTF-8")
}
tasks.withType<Javadoc> {
	options.encoding = "UTF-8"
}

tasks.withType<Jar> {
	from("../../LICENSE-APACHE")
	from("../../LICENSE-MIT")
}

allprojects {
	repositories {
		// Use jcenter for resolving dependencies.
		// You can declare any Maven/Ivy/file repository here.
		mavenCentral()
		maven(url = "https://jitpack.io")
	}
}

dependencies {
	implementation(project(":solarxr-protocol"))

	// This dependency is used internally,
	// and not exposed to consumers on their own compile classpath.
	implementation("com.google.flatbuffers:flatbuffers-java:22.10.26")
	implementation("commons-cli:commons-cli:1.11.0")
	implementation("com.fasterxml.jackson.core:jackson-databind:2.21.0")
	implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.21.0")

	implementation("com.github.jonpeterson:jackson-module-model-versioning:1.2.2")
	implementation("org.apache.commons:commons-math3:3.6.1")
	implementation("org.apache.commons:commons-lang3:3.20.0")
	implementation("org.apache.commons:commons-collections4:4.5.0")

	implementation("com.illposed.osc:javaosc-core:0.8")
	implementation("org.java-websocket:Java-WebSocket:1.+")
	implementation("com.melloware:jintellitype:1.+")
	implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.10.0")

	// 2.1.1 - of kache cause OSCQuery to fail on android.
	// Same goes for upgrading coroutines. kache prob upgrade coroutines too.
	// proceed with caution if you plan on upgrading that library
	implementation("com.mayakapps.kache:kache:2.1.0")
	implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1")

	api("com.github.loucass003:EspflashKotlin:v0.11.0")

	// Allow the use of reflection
	implementation(kotlin("reflect"))

	// Jitpack
	implementation("com.github.SlimeVR:oscquery-kt:566a0cba58")

	// For SteamVR driver detection
	implementation("io.ktor:ktor-client-core:2.3.13")
	implementation("io.ktor:ktor-client-cio:2.3.13")

	// NekoVR AI Drift Correction Engine & Dataset compression
	implementation(
		"com.microsoft.onnxruntime:${if (onnxRuntimeFlavor.get() == "nvidia") "onnxruntime_gpu" else "onnxruntime"}:$onnxRuntimeVersion",
	)
	implementation("com.github.luben:zstd-jni:1.5.6-8")

	testImplementation(kotlin("test"))
	// Use JUnit test framework
	testImplementation(platform("org.junit:junit-bom:6.0.2"))
	testImplementation("org.junit.jupiter:junit-jupiter")
	testImplementation("org.junit.platform:junit-platform-launcher")
}

tasks.test {
	useJUnitPlatform()
}

tasks.processResources {
	inputs.property("onnxRuntimeFlavor", onnxRuntimeFlavor)
	inputs.property("onnxRuntimeVersion", onnxRuntimeVersion)
	filesMatching("dev/slimevr/ai/onnx-runtime.properties") {
		expand("flavor" to onnxRuntimeFlavor.get(), "version" to onnxRuntimeVersion)
	}
	from("../../ml/artifacts/onnx-probe-v1") {
		into("dev/slimevr/ai/probe")
	}
	from("../../ml/artifacts/benchmark-small-v1") {
		into("dev/slimevr/ai/benchmark")
	}
	from({
		zipTree(configurations.runtimeClasspath.get().single { it.name.startsWith("onnxruntime") && it.extension == "jar" })
	}) {
		include("ThirdPartyNotices.txt")
		into("META-INF/licenses/onnxruntime")
	}
}

tasks.register<JavaExec>("datasetArchiveReport") {
	group = "verification"
	description = "Writes server-side validation reports for one or more .nvrdata archives"
	dependsOn(tasks.classes)
	mainClass.set("dev.slimevr.dataset.DatasetArchiveReportCommandKt")
	classpath = sourceSets.main.get().runtimeClasspath
	doFirst {
		val archiveProperty = providers.gradleProperty("datasetArchives").orNull
			?: error("Pass -PdatasetArchives=<path${File.pathSeparator}path>")
		val outputProperty = providers.gradleProperty("datasetArchiveReport").orNull
			?: layout.buildDirectory.file("reports/dataset-ready/server-pilots.json").get().asFile.path
		args = listOf("--output", outputProperty) + archiveProperty.split(File.pathSeparator).filter(String::isNotBlank)
	}
}

tasks.register<JavaExec>("generateDatasetPilots") {
	group = "verification"
	description = "Generates short simulated 5-tracker and mixed-transport 8-tracker pilot archives"
	dependsOn(tasks.classes)
	mainClass.set("dev.slimevr.dataset.DatasetPilotGeneratorCommandKt")
	classpath = sourceSets.main.get().runtimeClasspath
	val output = providers.gradleProperty("datasetPilotOutput")
		.orElse(layout.buildDirectory.dir("dataset-pilots").map { it.asFile.path })
	doFirst { args = listOf("--output", output.get()) }
}

tasks.register<JavaExec>("generateDatasetConformanceFixture") {
	group = "verification"
	description = "Generates the deterministic Kotlin-writer/Python-reader v1 conformance archive"
	dependsOn(tasks.classes)
	mainClass.set("dev.slimevr.dataset.DatasetConformanceFixtureCommandKt")
	classpath = sourceSets.main.get().runtimeClasspath
	val output = providers.gradleProperty("datasetConformanceOutput")
		.orElse(layout.buildDirectory.dir("dataset-conformance").map { it.asFile.path })
	doFirst { args = listOf("--output", output.get()) }
}

tasks.register<JavaExec>("onnxRuntimeProbe") {
	group = "verification"
	description = "Creates a real session and runs the packaged ONNX probe on -PonnxProbeProvider=<provider>"
	dependsOn(tasks.classes)
	mainClass.set("dev.slimevr.ai.OnnxRuntimeProbeCommand")
	classpath = sourceSets.main.get().runtimeClasspath
	javaLauncher.set(javaToolchains.launcherFor { languageVersion.set(JavaLanguageVersion.of(17)) })
	args(providers.gradleProperty("onnxProbeProvider").orElse("CPU").get())
}

tasks.register<JavaExec>("aiInferenceBenchmark") {
	group = "verification"
	description = "Benchmarks ONNX inference, server-tick submission, queue stability, utilization, and memory"
	dependsOn(tasks.classes)
	mainClass.set("dev.slimevr.ai.InferenceBenchmarkCommand")
	classpath = sourceSets.main.get().runtimeClasspath
	javaLauncher.set(javaToolchains.launcherFor { languageVersion.set(JavaLanguageVersion.of(17)) })
	doFirst {
		val benchmarkArgs = mutableListOf(
			"--provider", providers.gradleProperty("aiBenchmarkProvider").orElse("CPU").get(),
			"--output", providers.gradleProperty("aiBenchmarkOutput")
				.orElse(layout.buildDirectory.file("reports/ai-inference/benchmark.json").map { it.asFile.path }).get(),
			"--iterations", providers.gradleProperty("aiBenchmarkIterations").orElse("500").get(),
			"--warmup", providers.gradleProperty("aiBenchmarkWarmup").orElse("30").get(),
			"--submission-hz", providers.gradleProperty("aiBenchmarkSubmissionHz").orElse("100").get(),
		)
		providers.gradleProperty("aiBenchmarkModel").orNull?.let { benchmarkArgs += listOf("--model", it) }
		providers.gradleProperty("aiBenchmarkSidecar").orNull?.let { benchmarkArgs += listOf("--sidecar", it) }
		providers.gradleProperty("aiBenchmarkTrackers").orNull?.let { benchmarkArgs += listOf("--trackers", it) }
		providers.gradleProperty("aiBenchmarkContexts").orNull?.let { benchmarkArgs += listOf("--contexts", it) }
		providers.gradleProperty("aiBenchmarkHostId").orNull?.let { benchmarkArgs += listOf("--host-id", it) }
		args = benchmarkArgs
	}
}

tasks.register<JavaExec>("aiInferenceBenchmarkGate") {
	group = "verification"
	description = "Enforces the small-tier 10-slot/60-frame latency, GPU-memory, and queue policy"
	dependsOn("aiInferenceBenchmark")
	mainClass.set("dev.slimevr.ai.InferenceBenchmarkGateCommand")
	classpath = sourceSets.main.get().runtimeClasspath
	javaLauncher.set(javaToolchains.launcherFor { languageVersion.set(JavaLanguageVersion.of(17)) })
	doFirst {
		val benchmark = providers.gradleProperty("aiBenchmarkOutput")
			.orElse(layout.buildDirectory.file("reports/ai-inference/benchmark.json").map { it.asFile.path }).get()
		val gate = providers.gradleProperty("aiBenchmarkGateOutput")
			.orElse(layout.buildDirectory.file("reports/ai-inference/gate.json").map { it.asFile.path }).get()
		args = listOf(benchmark, gate) + listOfNotNull(providers.gradleProperty("aiBenchmarkReferenceHostId").orNull)
	}
}

tasks.register<JavaExec>("inferenceReadyReport") {
	group = "verification"
	description = "Aggregates and verifies all hash-pinned inference-ready evidence"
	dependsOn(tasks.classes)
	mainClass.set("dev.slimevr.ai.InferenceReadyReportCommand")
	classpath = sourceSets.main.get().runtimeClasspath
	javaLauncher.set(javaToolchains.launcherFor { languageVersion.set(JavaLanguageVersion.of(17)) })
	doFirst {
		val manifest = providers.gradleProperty("inferenceReadyEvidence").orNull
			?: error("Pass -PinferenceReadyEvidence=<evidence-manifest.json>")
		val output = providers.gradleProperty("inferenceReadyOutput")
			.orElse(layout.projectDirectory.file("models/ai/inference-ready-report.json").asFile.path).get()
		args = listOf(manifest, output)
	}
}

tasks.register<JavaExec>("shadowDogfoodGate") {
	group = "verification"
	description = "Validates real-player shadow sessions across required layout/activity cohorts"
	dependsOn(tasks.classes)
	mainClass.set("dev.slimevr.ai.ShadowDogfoodGateCommand")
	classpath = sourceSets.main.get().runtimeClasspath
	javaLauncher.set(javaToolchains.launcherFor { languageVersion.set(JavaLanguageVersion.of(17)) })
	doFirst {
		val source = providers.gradleProperty("shadowDogfoodEvidence").orNull
			?: error("Pass -PshadowDogfoodEvidence=<shadow-dogfood.json>")
		val output = providers.gradleProperty("shadowDogfoodGateOutput")
			.orElse(layout.buildDirectory.file("reports/ai-inference/shadow-dogfood-gate.json").map { it.asFile.path }).get()
		args = listOf(source, output)
	}
}
