/*
 * This file was generated by the Gradle "init" task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.3/userguide/java_library_plugin.html
 */
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import java.util.zip.ZipFile

plugins {
	kotlin("jvm")
	application
	id("com.gradleup.shadow")
	id("com.github.gmazzo.buildconfig")
}

kotlin {
	jvmToolchain {
		languageVersion.set(JavaLanguageVersion.of(17))
	}
}
java {
	toolchain {
		languageVersion.set(JavaLanguageVersion.of(17))
	}
}
tasks.withType<KotlinCompile> {
	compilerOptions {
		jvmTarget.set(JvmTarget.JVM_17)
		freeCompilerArgs.set(listOf("-Xvalue-classes"))
	}
}

// Set compiler to use UTF-8
tasks.withType<JavaCompile> {
	options.encoding = "UTF-8"
}
tasks.withType<Test> {
	systemProperty("file.encoding", "UTF-8")
}
tasks.withType<Javadoc> {
	options.encoding = "UTF-8"
}

allprojects {
	repositories {
		// Use jcenter for resolving dependencies.
		// You can declare any Maven/Ivy/file repository here.
		mavenCentral()
		maven(url = "https://jitpack.io")
		maven(url = "https://oss.sonatype.org/content/repositories/snapshots")
	}
}

dependencies {
	implementation(project(":server:core"))
	implementation(project(":solarxr-protocol"))

	implementation("commons-cli:commons-cli:1.11.0")
	implementation("org.apache.commons:commons-lang3:3.20.0")
	implementation("com.google.protobuf:protobuf-java:4.31.1")
	implementation("net.java.dev.jna:jna:5.+")
	implementation("net.java.dev.jna:jna-platform:5.+")
	implementation("com.fazecast:jSerialComm:2.11.3") {
		exclude(group = "com.fazecast", module = "android")
	}
	implementation("org.hid4java:hid4java:0.8.0")
}

tasks.shadowJar {
	minimize {
		exclude(dependency("com.fazecast:jSerialComm:.*"))
		exclude(dependency("net.java.dev.jna:.*:.*"))
		exclude(dependency("com.google.flatbuffers:flatbuffers-java:.*"))

		exclude(project(":server:core"))
		exclude(project(":solarxr-protocol"))
		exclude(dependency("com.microsoft.onnxruntime:.*:.*"))
	}
	archiveBaseName.set("slimevr")
	archiveClassifier.set("")
	archiveVersion.set("")
}

tasks.register("verifyInferenceDistributionContents") {
	group = "verification"
	description = "Verifies generated RPC, ONNX runtime/model metadata, and licenses in the desktop distribution JAR"
	dependsOn(tasks.shadowJar)
	doLast {
		val archive = tasks.shadowJar.get().archiveFile.get().asFile
		ZipFile(archive).use { zip ->
			val entries = zip.entries().asSequence().map { it.name }.toSet()
			val required = setOf(
				"dev/slimevr/desktop/Main.class",
				"dev/slimevr/ai/InstalledInferenceSmokeCommand.class",
				"solarxr_protocol/rpc/RpcMessage.class",
				"ai/onnxruntime/OrtEnvironment.class",
				"dev/slimevr/ai/probe/probe.onnx",
				"dev/slimevr/ai/probe/probe.onnx.json",
				"dev/slimevr/ai/probe/probe-fixture.json",
				"dev/slimevr/ai/probe/manifest.json",
				"dev/slimevr/ai/benchmark/small.onnx",
				"dev/slimevr/ai/benchmark/small.onnx.json",
				"META-INF/licenses/onnxruntime/ThirdPartyNotices.txt",
			)
			val missing = required - entries
			check(missing.isEmpty()) { "Desktop distribution is missing: ${missing.sorted()}" }
			check(entries.any { it.startsWith("ai/onnxruntime/native/") }) { "Desktop distribution has no ONNX native runtime" }
		}
	}
}

val prepareJpackageInput by tasks.registering(Sync::class) {
	dependsOn(tasks.shadowJar)
	from(tasks.shadowJar.flatMap { it.archiveFile })
	from("../../gui/out") { into("gui") }
	into(layout.buildDirectory.dir("jpackage-input"))
}

tasks.register<Exec>("jpackageImage") {
	group = "distribution"
	description = "Builds a self-contained server image with the packaged GUI assets and ONNX runtime"
	dependsOn(prepareJpackageInput, "verifyInferenceDistributionContents")
	val destination = layout.buildDirectory.dir("jpackage")
	doFirst {
		project.delete(destination)
		commandLine(
			javaToolchains.launcherFor { languageVersion.set(JavaLanguageVersion.of(17)) }.get().metadata.installationPath.file("bin/jpackage${if (System.getProperty("os.name").startsWith("Windows")) ".exe" else ""}").asFile,
			"--type", "app-image", "--name", "NekoVR-Server", "--dest", destination.get().asFile,
			"--input", layout.buildDirectory.dir("jpackage-input").get().asFile,
			"--main-jar", "slimevr.jar", "--main-class", "dev.slimevr.desktop.Main",
		)
	}
}

tasks.register<Exec>("installedInferenceSmoke") {
	group = "verification"
	description = "Runs managed import and every available provider from the packaged offline desktop JAR"
	dependsOn(tasks.shadowJar, "verifyInferenceDistributionContents")
	doFirst {
		val java = javaToolchains.launcherFor { languageVersion.set(JavaLanguageVersion.of(17)) }.get().executablePath.asFile
		val archive = tasks.shadowJar.get().archiveFile.get().asFile
		val output = layout.buildDirectory.file("reports/installed-inference-smoke.json").get().asFile
		environment("NEKOVR_OFFLINE_SMOKE", "1")
		commandLine(java, "-Djava.net.useSystemProxies=false", "-cp", archive, "dev.slimevr.ai.InstalledInferenceSmokeCommand", output)
	}
}
application {
	mainClass.set("dev.slimevr.desktop.Main")
}

buildConfig {
	useKotlinOutput { topLevelConstants = true }
	packageName("dev.slimevr.desktop")

	val gitCommitHash = providers.exec {
		commandLine("git", "rev-parse", "--short=8", "HEAD")
	}.standardOutput.asText.get().trim()
	val gitVersionTag = providers.exec {
		commandLine("git", "--no-pager", "tag", "--sort", "-taggerdate", "--points-at", "HEAD")
	}.standardOutput.asText.get().trim()
	val gitIsClean = providers.exec {
		commandLine("git", "status", "--porcelain")
	}.standardOutput.asText.get().trim().isEmpty()
	buildConfigField("String", "GIT_COMMIT_HASH", "\"${gitCommitHash}\"")
	buildConfigField("String", "GIT_VERSION_TAG", "\"${gitVersionTag}\"")
	buildConfigField("boolean", "GIT_CLEAN", gitIsClean.toString())
}

tasks.run<JavaExec> {
	standardInput = System.`in` // this is not working
	args = listOf("run")
}
